spring:
  main:
    allow-circular-references: true
  application:
    name: Monofi
  profiles:
    active: ${ACTIVE_PROFILE:dev}
    include:
      - common
      - database
      - security
  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password:
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
twilio:
  account_sid: 
  auth_token: 
  trial_number: 

stripe:
  apiKey:
    secret: 
    publishable: 
