spring:
  main:
    allow-circular-references: true
  application:
    name: Monofi
  profiles:
    active: ${ACTIVE_PROFILE:dev}
    include:
      - common
      - database
      - security
  mail:
    host: smtp.gmail.com
    port: 587
    username: serdaraktolga77@gmail.com
    password: mmqgwkruntfnjleh
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
twilio:
  account_sid: AC95a99a41f363dc2ff6fe1131d83d5b08
  auth_token: 043e891ff206b9724d562ce1770f63ab
  trial_number: +19148615996

