spring:
  application:
    name: Monofi
  profiles:
    active: ${ACTIVE_PROFILE:dev}
    include:
      - common
      - database
      - security
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password: 
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
